#power.py
#this file is just for the power dictionary

# blank entry
#'': {'Name': '', 'Tier': , 'Prereq': []},

power = {
'brawn1': {'Name': 'Tier1 Strength', 'Tier': 1, 'Prereq': []},
'speed1': {'Name': 'Tier1 Speed', 'Tier': 1, 'Prereq': []},
'endurance1': {'Name': 'Tier1 Endurance', 'Tier': 1, 'Prereq': []},
'memory1': {'Name': 'Tier1 Memory', 'Tier': 1, 'Prereq': []},
'celerity1': {'Name': 'Tier1 Mental Celerity', 'Tier': 1, 'Prereq': []},
'clarity1': {'Name': 'Tier1 Mental Clarity', 'Tier': 1, 'Prereq': []},
'regen1': {'Name': 'Tier1 Regeneration', 'Tier': 1, 'Prereq': []},
'pain1': {'Name': 'Tier1 Pain Tolerance', 'Tier': 1, 'Prereq': []},
'invis1': {'Name': 'Invisibility (Tier1)', 'Tier': 1, 'Prereq': []},
'vision1': {'Name': 'Tier1 Vision', 'Tier': 1, 'Prereq': []},
'hearing1': {'Name': 'Tier1 Aural Faculty', 'Tier': 1, 'Prereq': []},
'smell1': {'Name': 'Tier1 Olfactory Sense', 'Tier': 1, 'Prereq': []},
'taste1': {'Name': 'Tier1 Gustatory Ability', 'Tier': 1, 'Prereq': []},
'touch1': {'Name': 'Tier1 Tactile Reception', 'Tier': 1, 'Prereq': []},
'space1': {'Name': 'Tier1 Proprioception', 'Tier': 1, 'Prereq': []},


'brawn2': {'Name': 'Tier2 Strength', 'Tier': 2, 'Prereq': ['brawn1']},
'speed2': {'Name': 'Tier2 Speed', 'Tier': 2, 'Prereq': ['speed1']},
'endurance2': {'Name': 'Tier2 Endurance', 'Tier': 2, 'Prereq': ['endurance1']},
'memory2': {'Name': 'Tier2 Memory', 'Tier': 2, 'Prereq': ['memory1']},
'celerity2': {'Name': 'Tier2 Mental Celerity', 'Tier': 2, 'Prereq': ['celerity1']},
'clarity2': {'Name': 'Tier2 Mental Clarity', 'Tier': 2, 'Prereq': ['clarity1']},
'regen2': {'Name': 'Tier2 Regeneration', 'Tier': 2, 'Prereq': ['regen1']},
'pain2': {'Name': 'Tier2 Pain Tolerance', 'Tier': 2, 'Prereq': ['pain1']},
'invis2': {'Name': 'Invisibility (Tier2)', 'Tier': 2, 'Prereq': ['invis1']},
'vision2': {'Name': 'Tier2 Vision', 'Tier': 2, 'Prereq': ['vision1']},
'hearing2': {'Name': 'Tier2 Aural Faculty', 'Tier': 2, 'Prereq': ['hearing1']},
'smell2': {'Name': 'Tier2 Olfactory Sense', 'Tier': 2, 'Prereq': ['smell1']},
'taste2': {'Name': 'Tier2 Gustatory Ability', 'Tier': 2, 'Prereq': ['taste1']},
'touch2': {'Name': 'Tier2 Tactile Reception', 'Tier': 2, 'Prereq': ['touch1']},
'space2': {'Name': 'Tier2 Proprioception', 'Tier': 2, 'Prereq': ['space1']},


'brawn3': {'Name': 'Tier3 Strength', 'Tier': 3, 'Prereq': ['brawn2']},
'speed3': {'Name': 'Tier3 Speed', 'Tier': 3, 'Prereq': ['speed2']},
'endurance3': {'Name': 'Tier3 Endurance', 'Tier': 3, 'Prereq': ['endurance2']},
'memory3': {'Name': 'Tier3 Memory', 'Tier': 3, 'Prereq': ['memory2']},
'celerity3': {'Name': 'Tier3 Mental Celerity', 'Tier': 3, 'Prereq': ['celerity2']},
'clarity3': {'Name': 'Tier3 Mental Clarity', 'Tier': 3, 'Prereq': ['clarity2']},
'regen3': {'Name': 'Tier3 Regeneration', 'Tier': 3, 'Prereq': ['regen2']},
'pain3': {'Name': 'Tier3 Pain Tolerance', 'Tier': 3, 'Prereq': ['pain2']},
'invis3': {'Name': 'Invisibility (Tier3)', 'Tier': 3, 'Prereq': ['invis2']},
'vision3': {'Name': 'Tier3 Vision', 'Tier': 3, 'Prereq': ['vision2']},
'hearing3': {'Name': 'Tier3 Aural Faculty', 'Tier': 3, 'Prereq': ['hearing2']},
'smell3': {'Name': 'Tier3 Olfactory Sense', 'Tier': 3, 'Prereq': ['smell2']},
'taste3': {'Name': 'Tier3 Gustatory Ability', 'Tier': 3, 'Prereq': ['taste2']},
'touch3': {'Name': 'Tier3 Tactile Reception', 'Tier': 3, 'Prereq': ['touch2']},
'space3': {'Name': 'Tier3 Proprioception', 'Tier': 3, 'Prereq': ['space2']},


'brawn4': {'Name': 'Tier4 Strength', 'Tier': 4, 'Prereq': ['brawn3','endurance1', 'space1', 'regen1']},
'speed4': {'Name': 'Tier4 Speed', 'Tier': 4, 'Prereq': ['speed3','vision1', 'space1', 'celerity1']},
'endurance4': {'Name': 'Tier4 Endurance', 'Tier': 4, 'Prereq': ['endurance3', 'brawn1', 'touch1', 'pain1']},
'memory4': {'Name': 'Tier4 Memory', 'Tier': 4, 'Prereq': ['memory3', 'clarity1', 'celerity1']},
'celerity4': {'Name': 'Tier4 Mental Celerity', 'Tier': 4, 'Prereq': ['celerity3', 'speed1', 'memory1', 'clarity1']},
'clarity4': {'Name': 'Tier4 Mental Clarity', 'Tier': 4, 'Prereq': ['clarity3', 'endurance1', 'memory1', 'celerity1']},
'regen4': {'Name': 'Tier4 Regeneration', 'Tier': 4, 'Prereq': ['regen3', 'speed1', 'space1', 'pain1']},
'pain4': {'Name': 'Tier4 Pain Tolerance', 'Tier': 4, 'Prereq': ['pain3', 'touch1']},
'invis4': {'Name': 'Invisibility (Tier4)', 'Tier': 4, 'Prereq': ['invis3', 'clarity1', 'celerity1', 'space1']},
'vision4': {'Name': 'Tier4 Vision', 'Tier': 4, 'Prereq': ['vision3', 'clarity1', 'celerity1']},
'hearing4': {'Name': 'Tier4 Aural Faculty', 'Tier': 4, 'Prereq': ['hearing3', 'clarity1', 'celerity1']},
'smell4': {'Name': 'Tier4 Olfactory Sense', 'Tier': 4, 'Prereq': ['smell3', 'clarity1', 'celerity1']},
'taste4': {'Name': 'Tier4 Gustatory Ability', 'Tier': 4, 'Prereq': ['taste3', 'clarity1', 'celerity1']},
'touch4': {'Name': 'Tier4 Tactile Reception', 'Tier': 4, 'Prereq': ['touch3', 'clarity1', 'celerity1']},
'space4': {'Name': 'Tier4 Proprioception', 'Tier': 4, 'Prereq': ['space3', 'clarity1', 'celerity1']},


'brawn5': {'Name': 'Tier5 Strength', 'Tier': 5, 'Prereq': ['brawn4']},
'speed5': {'Name': 'Tier5 Speed', 'Tier': 5, 'Prereq': ['speed4']},
'endurance5': {'Name': 'Tier5 Endurance', 'Tier': 5, 'Prereq': ['endurance4']},
'memory5': {'Name': 'Tier5 Memory', 'Tier': 5, 'Prereq': ['memory4']},
'celerity5': {'Name': 'Tier5 Mental Celerity', 'Tier': 5, 'Prereq': ['celerity4']},
'clarity5': {'Name': 'Tier5 Mental Clarity', 'Tier': 5, 'Prereq': ['clarity4']},
'regen5': {'Name': 'Tier5 Regeneration', 'Tier': 5, 'Prereq': ['regen4']},
'pain5': {'Name': 'Tier5 Pain Tolerance', 'Tier': 5, 'Prereq': ['pain4']},
'invis5': {'Name': 'Invisibility (Tier5)', 'Tier': 5, 'Prereq': ['invis4']},
'vision5': {'Name': 'Tier5 Vision', 'Tier': 5, 'Prereq': ['vision4']},
'hearing5': {'Name': 'Tier5 Aural Faculty', 'Tier': 5, 'Prereq': ['hearing4']},
'smell5': {'Name': 'Tier5 Olfactory Sense', 'Tier': 5, 'Prereq': ['smell4']},
'taste5': {'Name': 'Tier5 Gustatory Ability', 'Tier': 5, 'Prereq': ['taste4']},
'touch5': {'Name': 'Tier5 Tactile Reception', 'Tier': 5, 'Prereq': ['touch4']},
'space5': {'Name': 'Tier5 Proprioception', 'Tier': 5, 'Prereq': ['space4']},


'brawn6': {'Name': 'Tier6 Strength', 'Tier': 6, 'Prereq': ['brawn5']},
'speed6': {'Name': 'Tier6 Speed', 'Tier': 6, 'Prereq': ['speed5']},
'endurance6': {'Name': 'Tier6 Endurance', 'Tier': 6, 'Prereq': ['endurance5']},
'memory6': {'Name': 'Tier6 Memory', 'Tier': 6, 'Prereq': ['memory5']},
'celerity6': {'Name': 'Tier6 Mental Celerity', 'Tier': 6, 'Prereq': ['celerity5']},
'clarity6': {'Name': 'Tier6 Mental Clarity', 'Tier': 6, 'Prereq': ['clarity5']},
'regen6': {'Name': 'Tier6 Regeneration', 'Tier': 6, 'Prereq': ['regen5']},
'pain6': {'Name': 'Tier6 Pain Tolerance', 'Tier': 6, 'Prereq': ['pain5']},
'invis6': {'Name': 'Invisibility (Tier6)', 'Tier': 6, 'Prereq': ['invis5']},
'vision6': {'Name': 'Tier6 Vision', 'Tier': 6, 'Prereq': ['vision5']},
'hearing6': {'Name': 'Tier6 Aural Faculty', 'Tier': 6, 'Prereq': ['hearing5']},
'smell6': {'Name': 'Tier6 Olfactory Sense', 'Tier': 6, 'Prereq': ['smell5']},
'taste6': {'Name': 'Tier6 Gustatory Ability', 'Tier': 6, 'Prereq': ['taste5']},
'touch6': {'Name': 'Tier6 Tactile Reception', 'Tier': 6, 'Prereq': ['touch5']},
'space6': {'Name': 'Tier6 Proprioception', 'Tier': 6, 'Prereq': ['space5']},


'brawn7': {'Name': 'Tier7 Strength', 'Tier': 7, 'Prereq': ['brawn6', 'endurance3', 'space3', 'regen3']},
'speed7': {'Name': 'Tier7 Speed', 'Tier': 7, 'Prereq': ['speed6', 'endurance1', 'space3', 'celerity3']},
'endurance7': {'Name': 'Tier7 Endurance', 'Tier': 7, 'Prereq': ['endurance6', 'brawn3', 'touch3', 'pain3']},
'memory7': {'Name': 'Tier7 Memory', 'Tier': 7, 'Prereq': ['memory6', 'speed1', 'clarity3', 'celerity3']},
'celerity7': {'Name': 'Tier7 Mental Celerity', 'Tier': 7, 'Prereq': ['celerity6', 'speed3', 'memory3', 'clarity3']},
'clarity7': {'Name': 'Tier7 Mental Clarity', 'Tier': 7, 'Prereq': ['clarity6', 'endurance3', 'memory3', 'celerity3']},
'regen7': {'Name': 'Tier7 Regeneration', 'Tier': 7, 'Prereq': ['regen6', 'speed3', 'space3', 'pain3']},
'pain7': {'Name': 'Tier7 Pain Tolerance', 'Tier': 7, 'Prereq': ['pain6', 'endurance1', 'touch3', 'regen1']},
'invis7': {'Name': 'Invisibility (Tier7)', 'Tier': 7, 'Prereq': ['invis6', 'space3', 'clarity3', 'celerity3']},
'vision7': {'Name': 'Tier7 Vision', 'Tier': 7, 'Prereq': ['vision6', 'memory1', 'clarity3', 'celerity3']},
'hearing7': {'Name': 'Tier7 Aural Faculty', 'Tier': 7, 'Prereq': ['hearing6', 'memory1', 'clarity3', 'celerity3']},
'smell7': {'Name': 'Tier7 Olfactory Sense', 'Tier': 7, 'Prereq': ['smell6', 'memory1', 'clarity3', 'celerity3']},
'taste7': {'Name': 'Tier7 Gustatory Ability', 'Tier': 7, 'Prereq': ['taste6', 'memory1', 'clarity3', 'celerity3']},
'touch7': {'Name': 'Tier7 Tactile Reception', 'Tier': 7, 'Prereq': ['touch6', 'space1', 'clarity3', 'celerity3']},
'space7': {'Name': 'Tier7 Proprioception', 'Tier': 7, 'Prereq': ['space6', 'memory3', 'clarity3', 'celerity3']},


'brawn8': {'Name': 'Tier8 Strength', 'Tier': 8, 'Prereq': ['brawn7']},
'speed8': {'Name': 'Tier8 Speed', 'Tier': 8, 'Prereq': ['speed7']},
'endurance8': {'Name': 'Tier8 Endurance', 'Tier': 8, 'Prereq': ['endurance7']},
'memory8': {'Name': 'Tier8 Memory', 'Tier': 8, 'Prereq': ['memory7']},
'celerity8': {'Name': 'Tier8 Mental Celerity', 'Tier': 8, 'Prereq': ['celerity7']},
'clarity8': {'Name': 'Tier8 Mental Clarity', 'Tier': 8, 'Prereq': ['clarity7']},
'regen8': {'Name': 'Tier8 Regeneration', 'Tier': 8, 'Prereq': ['regen7']},
'pain8': {'Name': 'Tier8 Pain Tolerance', 'Tier': 8, 'Prereq': ['pain7']},
'invis8': {'Name': 'Invisibility (Tier8)', 'Tier': 8, 'Prereq': ['invis7']},
'vision8': {'Name': 'Tier8 Vision', 'Tier': 8, 'Prereq': ['vision7']},
'hearing8': {'Name': 'Tier8 Aural Faculty', 'Tier': 8, 'Prereq': ['hearing7']},
'smell8': {'Name': 'Tier8 Olfactory Sense', 'Tier': 8, 'Prereq': ['smell7']},
'taste8': {'Name': 'Tier8 Gustatory Ability', 'Tier': 8, 'Prereq': ['taste7']},
'touch8': {'Name': 'Tier8 Tactile Reception', 'Tier': 8, 'Prereq': ['touch7']},
'space8': {'Name': 'Tier8 Proprioception', 'Tier': 8, 'Prereq': ['space7']},


'brawn9': {'Name': 'Tier9 Strength', 'Tier': 9, 'Prereq': ['brawn8']},
'speed9': {'Name': 'Tier9 Speed', 'Tier': 9, 'Prereq': ['speed8']},
'endurance9': {'Name': 'Tier9 Endurance', 'Tier': 9, 'Prereq': ['endurance8']},
'memory9': {'Name': 'Tier9 Memory', 'Tier': 9, 'Prereq': ['memory8']},
'celerity9': {'Name': 'Tier9 Mental Celerity', 'Tier': 9, 'Prereq': ['celerity8']},
'clarity9': {'Name': 'Tier9 Mental Clarity', 'Tier': 9, 'Prereq': ['clarity8']},
'regen9': {'Name': 'Tier9 Regeneration', 'Tier': 9, 'Prereq': ['regen8']},
'pain9': {'Name': 'Tier9 Pain Tolerance', 'Tier': 9, 'Prereq': ['pain8']},
'invis9': {'Name': 'Invisibility (Tier9)', 'Tier': 9, 'Prereq': ['invis8']},
'vision9': {'Name': 'Tier9 Vision', 'Tier': 9, 'Prereq': ['vision8']},
'hearing9': {'Name': 'Tier9 Aural Faculty', 'Tier': 9, 'Prereq': ['hearing8']},
'smell9': {'Name': 'Tier9 Olfactory Sense', 'Tier': 9, 'Prereq': ['smell8']},
'taste9': {'Name': 'Tier9 Gustatory Ability', 'Tier': 9, 'Prereq': ['taste8']},
'touch9': {'Name': 'Tier9 Tactile Reception', 'Tier': 9, 'Prereq': ['touch8']},
'space9': {'Name': 'Tier9 Proprioception', 'Tier': 9, 'Prereq': ['space8']},


'brawn10': {'Name': 'Tier10 Strength', 'Tier': 10, 'Prereq': ['brawn9', 'endurance6', 'regen6', 'pain3', 'space6']},
'speed10': {'Name': 'Tier10 Speed', 'Tier': 10, 'Prereq': ['speed9', 'endurance3', 'vision3', 'celerity6', 'space6']},
'endurance10': {'Name': 'Tier10 Endurance', 'Tier': 10, 'Prereq': ['endurance9', 'brawn6', 'touch6', 'pain6']},
'memory10': {'Name': 'Tier10 Memory', 'Tier': 10, 'Prereq': ['memory9', 'speed3', 'clarity6', 'celerity6']},
'celerity10': {'Name': 'Tier10 Mental Celerity', 'Tier': 10, 'Prereq': ['celerity9', 'speed6', 'memory6', 'clarity6']},
'clarity10': {'Name': 'Tier10 Mental Clarity', 'Tier': 10, 'Prereq': ['clarity9', 'endurance6', 'memory6', 'celerity6']},
'regen10': {'Name': 'Tier10 Regeneration', 'Tier': 10, 'Prereq': ['regen9', 'speed6', 'memory3', 'pain6', 'space6']},
'pain10': {'Name': 'Tier10 Pain Tolerance', 'Tier': 10, 'Prereq': ['pain9', 'endurance3', 'touch6', 'regen3']},
'invis10': {'Name': 'Invisibility (Tier10)', 'Tier': 10, 'Prereq': ['invis9', 'memory3', 'clarity6', 'celerity6', 'space6']},
'vision10': {'Name': 'Tier10 Vision', 'Tier': 10, 'Prereq': ['vision9', 'memory3', 'clarity6', 'celerity6']},
'hearing10': {'Name': 'Tier10 Aural Faculty', 'Tier': 10, 'Prereq': ['hearing9', 'memory3', 'clarity6', 'celerity6']},
'smell10': {'Name': 'Tier10 Olfactory Sense', 'Tier': 10, 'Prereq': ['smell9', 'memory3', 'clarity6', 'celerity6']},
'taste10': {'Name': 'Tier10 Gustatory Ability', 'Tier': 10, 'Prereq': ['taste9', 'memory3', 'clarity6', 'celerity6']},
'touch10': {'Name': 'Tier10 Tactile Reception', 'Tier': 10, 'Prereq': ['touch9', 'pain3', 'clarity6', 'celerity6', 'space3']},
'space10': {'Name': 'Tier10 Proprioception', 'Tier': 10, 'Prereq': ['space9', 'memory6', 'clarity6', 'celerity6']},
}
